configuration:
  - Debug
  - Release

image: Visual Studio 2017

environment:
  RunCodeAnalysis: true
  TreatWarningsAsErrors: true

branches:
  only:
    - master
    - develop

skip_tags: true

notifications:
  - provider: GitHubPullRequest
    on_build_success: true
    on_build_failure: true

cache:
  - packages -> **\packages.config

install:
  - ps: |
      $ErrorActionPreference = 'Stop'
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
      Install-Module -Name platyPS -Repository PSGallery -SkipPublisherCheck -Force

before_build:
  - nuget restore
  - ps: New-ExternalHelp -Path $env:APPVEYOR_BUILD_FOLDER\docs\VSSetup -OutputPath $env:APPVEYOR_BUILD_FOLDER\src\VSSetup.PowerShell\bin\$env:CONFIGURATION -Force

after_build:
  - 7z a bin\%CONFIGURATION%\VSSetup.zip %APPVEYOR_BUILD_FOLDER%\src\VSSetup.PowerShell\bin\%CONFIGURATION%\*.dll
  - 7z a bin\%CONFIGURATION%\VSSetup.zip %APPVEYOR_BUILD_FOLDER%\src\VSSetup.PowerShell\bin\%CONFIGURATION%\*.dll-Help.xml
  - 7z a bin\%CONFIGURATION%\VSSetup.zip %APPVEYOR_BUILD_FOLDER%\src\VSSetup.PowerShell\bin\%CONFIGURATION%\about_*.help.txt
  - 7z a bin\%CONFIGURATION%\VSSetup.zip %APPVEYOR_BUILD_FOLDER%\src\VSSetup.PowerShell\bin\%CONFIGURATION%\VSSetup.*

test:
  assemblies:
    - '**\bin\$(configuration)\*.test.dll'

artifacts:
  - path: bin\$(configuration)\VSSetup.zip
    name: VSSetup

  - path: src\VSSetup\bin\$(configuration)\*.nupkg
    name: package

deploy:
  - provider: GitHub
    auth_token:
      secure: 5K94QY8dHKlbjvlBpQaXwAkmDf+LQE3g5WlU9snnNMjDjf0UT4xDoOBCLWcmwZOm
    artifact: VSSetup
    on:
      branch: master
      configuration: Release

  - provider: NuGet
    server: https://powershellgallery.com
    api_key:
      secure: 4STrzCp6wDsDBj/wCtmImMVL7wUI8DCGjdMBXGqQf9JZJ8LjmW5YSY8wtcHAv0XW
    artifact: package
    skip_symbols: true
    on:
      branch: master
      configuration: Release

  - provider: NuGet
    server: https://nuget.smbsrc.net/
    api_key:
      secure: WPxjuSouwbCdM6I771BfIbOk8gA883+l9RKUCfFknaUT1vYPmTpT2ABF9r+J0JgR
    artifact: /.*\.symbols\.nupkg/
    on:
      branch: master
      configuration: Release

# vim: set ai et st=2 sts=2 sw=2:
